# Generated by Django 5.0.6 on 2024-06-18 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jugar', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='jugador',
            name='puntaje',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='repartidor',
            name='puntaje',
            field=models.IntegerField(default=0),
        ),
    ]
