# Generated by Django 5.0.6 on 2024-06-18 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jugar', '0002_jugador_puntaje_repartidor_puntaje'),
    ]

    operations = [
        migrations.AddField(
            model_name='jugador',
            name='nombre',
            field=models.CharField(default=None, max_length=50),
        ),
        migrations.AlterField(
            model_name='jugador',
            name='carta',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='repartidor',
            name='carta',
            field=models.CharField(max_length=200),
        ),
    ]
