# Generated by Django 5.0.6 on 2024-06-18 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jugar', '0003_jugador_nombre_alter_jugador_carta_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='repartidor',
            name='nombre',
            field=models.CharField(default=None, max_length=50),
        ),
    ]
